# Generated by Django 4.1.7 on 2023-04-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknown', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('isRetired', models.BooleanField(default=False)),
                ('idOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dao.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
