# Generated by Django 4.1.7 on 2023-04-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(choices=[('br', 'Brazilian'), ('en', 'American'), ('ar', 'Argentinian')], default='br', max_length=2),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(default='unknown', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='unknown', max_length=50, unique=True),
        ),
    ]
